
name: Build and compile LaTeX documentation and release PDF

on:
  push:
    tags:
      - 'v*.*.*'

env:
    FILE_NAME: Latex-Documentation
    REPO: ${{ secrets.OWNER }}/${{ secrets.REPO }}
      
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Install ghostscript
        run: sudo apt-get install -y ghostscript

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: dokument.tex
      
      
      - name: Rename generated pdf file
        run: mv dokument.pdf ${{env.FILE_NAME}}.pdf
      
      - name: Compress PDF
        run: gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 -dNOPAUSE -dQUIET -dBATCH -dPrinted=false -sOutputFile="${{env.FILE_NAME}}-compressed.pdf" "${{env.FILE_NAME}}.pdf"

      - run: |
          newest_tag=$(curl -s https://api.github.com/repos/${{env.REPO}}/releases/latest | jq -r '.tag_name')
          echo "NEWEST_TAG=$newest_tag" >> $GITHUB_ENV


      - name: Release the pdf
        uses: ncipollo/release-action@v1
        with:
            artifacts: "${{env.FILE_NAME}}.pdf, ${{env.FILE_NAME}}-compressed.pdf"
            allowUpdates: true

      - name: Release documentaion on other repo
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.NEWEST_TAG}}
          files: |
            ./${{env.FILE_NAME}}.pdf
            ./${{env.FILE_NAME}}-compressed.pdf
          repository: ${{env.REPO}}
          token: ${{ secrets.PAT }}